name: Terraform CI (Training)

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.tf'
      - '.github/workflows/**'

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: training-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt 

      - name: Terraform Validate
        run: terraform validate

