name: terraform-cd

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: training-terraform
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Setup Terraform 
       uses: hashicorp/setup=terraform@v3

     - name: Terraform Init
       uses: terraform init

     - name: Terraform Apply
       uses: terraform apply -auto-approve -var-file ="envs/dev.tfvars"
